## Numpy tutorial

*** In Python, NumPy (Numerical Python) is a powerful library used for working with numerical data, particularly large arrays and matrices. It is widely used in fields such as data analysis, machine learning, scientific computing, and engineering. ***

* Efficient Array Operations
* Support for Multi-Dimensional Arrays
* Mathematical Functions
* Linear Algebra Operations
* Broadcasting
* Random Number Generation
* Efficient Memory Usage
* Compatibility with Other Libraries
* Easy Interfacing with External Data


### How to install

In [1]:
pip install numpy #already installed

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#already'


In [2]:
import numpy as np 

In [3]:
list1 = [1,2,3,4,5,6]
array1 = np.array (list1) 

In [4]:
array1

array([1, 2, 3, 4, 5, 6])

# diamentional array (1d),(2d)
* arange reshape,ones,zeros functions 

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1 = np.array (list1,dtype="U32")
print(array1)

['1' '2' '3' '4' '5' '6']


In [7]:
array1 = np.array (list1,dtype=float)
print(array1)

[1. 2. 3. 4. 5. 6.]


In [8]:
array1 = np.array (list1,dtype=int)
print(array1)

[1 2 3 4 5 6]


In [9]:
import numpy as np
list1 = [[1,3,4] , [4,3,4,] , [2,3,4, ]]
array1 = np.array(list1)
print(array1)

[[1 3 4]
 [4 3 4]
 [2 3 4]]


In [10]:
import numpy as np
array1 = np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [11]:
import numpy as np
array1 = np.arange(11,17) .reshape((2,3))
print(array1)

[[11 12 13]
 [14 15 16]]


In [12]:
array1 = np.zeros((4,2))
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
array1 = np.zeros((4))
print(array1)

[0. 0. 0. 0.]


In [14]:
array1 = np.ones((4))
print(array1)

[1. 1. 1. 1.]


In [15]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Perform element-wise operations
arr_squared = arr ** 2

# Statistical operations
mean = np.mean(arr)
std_dev = np.std(arr)

# Create a 2D array (matrix)
matrix = np.array([[1, 2], [3, 4]])

# Matrix multiplication
result = np.dot(matrix, matrix)

print("Array:", arr)
print("Squared Array:", arr_squared)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Matrix multiplication result:\n", result)


Array: [1 2 3 4 5]
Squared Array: [ 1  4  9 16 25]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Matrix multiplication result:
 [[ 7 10]
 [15 22]]
