## Attributes of numpy

Attribute of numpy
1) ndim
2) size
3) dtype
4) shape
5) itemsize

In [1]:
import numpy as np
list1 = [2,5,6,4,7]
array1 = np.array(list1)
print(array1)
array1.ndim

[2 5 6 4 7]


1

In [2]:
import numpy as np
list1 = [2,5,6,4,7]
array1 = np.array(list1)
print(array1)
array1.size

[2 5 6 4 7]


5

In [3]:
import numpy as np
list1 = [2,5,6,4], [2,5,6,4]
array1 = np.array(list1)
print(array1)
array1.ndim

[[2 5 6 4]
 [2 5 6 4]]


2

In [4]:
import numpy as np
list1 = [2,5,6,4], [2,5,6,4]
array1 = np.array(list1)
print(array1)
array1.size

[[2 5 6 4]
 [2 5 6 4]]


8

In [5]:
import numpy as np
list1 = [[2,5,6,4], [2,5,6,4]]
array1 = np.array(list1)
print(array1)
array1.dtype

[[2 5 6 4]
 [2 5 6 4]]


dtype('int32')

In [6]:
import numpy as np
list3 = [[[2,5,6,4], [2,5,6,4], [2,5,6,4]]]
array3 = np.array(list3)
print(array3)
array1.shape

[[[2 5 6 4]
  [2 5 6 4]
  [2 5 6 4]]]


(2, 4)

### Idexing in numpy

In [7]:
import numpy as np
array1 = np.array([2,5,6,4,7])
print(array1[0])
print(array1[-1])


2
7


In [8]:
import numpy as np
array1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array1[1,2])
print(array1[1,:])
print(array1[:,1])

60
[40 50 60]
[20 50 80]


### Slicing in numpy

In [9]:
import numpy as np
array1 = np.array([10,20,30,40,50,60,70]) #One dimential
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])
print(array1[::-1])

[20 30]
[20 40 60]
[70 60]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [10]:
import numpy as np
array1 = np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]]) #Two dimential
print(array1[1,])
print(array1[:,1])
print(array1[1:3 ,1:3])
print(array1[1:3,])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 17]
 [26 27]
 [36 37]
 [46 47]]
[26 36]
[[25]
 [35]]
